/* 北投旅圖：景點／美食／行程共用 JSON、Excel 匯入與 Excel 匯出。
 * Excel 採「主資料、交通路線、行程分段、延伸閱讀」分表，避免要求小編編輯 JSON。
 * 不執行 DDL；既有紀錄依 ID 更新且保留上架狀態，新資料一律草稿。 */
(function(global){'use strict';
const CATEGORIES={spots:'景點',foods:'美食',trips:'行程'};
const MAIN='主資料',ROUTES='交通路線',SECTIONS='行程分段',RELATED='延伸閱讀',HELP='使用說明';
const routeColumns=['資料編號','路線序號','路線名稱','啟用','節點序號','節點類型','站名','路線／車號','方向','分鐘','距離','備註'];
const sectionColumns=['資料編號','段落序號','時間','段落標題','段落說明','顯示圖片','圖片網址','圖片來源'];
const relatedColumns=['資料編號','排序','文章類型','關聯文章編號'];
const statusHeading='上架狀態（僅供參考）';
const categoryLabel=type=>CATEGORIES[type]||'內容';
function fields(type){if(!CATEGORIES[type])throw Error('不支援的匯入分類');return global.MetroCmsSchema.fields(type).filter(([key])=>!['transport_routes','trip_sections','is_published'].includes(key));}
const LEGACY_TRANSPORT=new Set(['transport_metro','transport_bus','transport_car']);
function mainColumns(type){return fields(type).filter(([key])=>!LEGACY_TRANSPORT.has(key)).map(([key,label])=>({key,label}));}
function routeSummary(record){if(!Array.isArray(record.transport_routes)||!record.transport_routes.length)return '';return record.transport_routes.map(route=>[route.title||'交通路線',...(route.steps||[]).map(step=>{const parts=[step.name,step.line,step.direction,step.duration?step.duration+'分鐘':'',step.distance,step.detail].filter(Boolean);return (step.type||'站點')+'｜'+parts.join('・');})].join('\n')).join('\n\n');}
function getXlsx(){if(!global.XLSX?.utils?.aoa_to_sheet||!global.XLSX?.read||!global.XLSX?.writeFile)throw Error('Excel 元件未載入，請確認網路可連接 CDN，或先使用 JSON 匯入。');return global.XLSX;}
function safeText(value){return value===null||value===undefined?'':String(value);}
function str(value){return safeText(value).trim();}
function sheet(xlsx,headers,rows){const ws=xlsx.utils.aoa_to_sheet([headers,...rows]);ws['!cols']=headers.map((name,i)=>({wch:Math.min(48,Math.max(i===0?19:12,name.length*2+4,rows.some(r=>safeText(r[i]).length>40)?38:18))}));ws['!autofilter']={ref:ws['!ref']};ws['!rows']=[{hpt:27}];return ws;}
function routeRows(records){const result=[];for(const r of records){if(!Array.isArray(r.transport_routes))continue;r.transport_routes.forEach((route,i)=>{(route?.steps||[]).forEach((step,j)=>result.push([r.id,i+1,route.title||'',route.enabled===false?'否':'是',j+1,step.type||'步行',step.name||'',step.line||'',step.direction||'',step.duration??'',step.distance||'',step.detail||'']));});}return result;}
function sectionRows(records){const result=[];for(const r of records){if(!Array.isArray(r.trip_sections))continue;r.trip_sections.forEach((s,i)=>result.push([r.id,s.order||i+1,s.time||'',s.title||'',s.text||s.description||'',s.show_image===false?'否':'是',s.image||s.image_url||'',s.image_source||s.source||'']));}return result;}
function relatedRows(records){const result=[];for(const r of records){(Array.isArray(r.related_items)?r.related_items:[]).forEach((item,i)=>result.push([r.id,i+1,item.type||'',item.id||'']));}return result;}
function toWorkbook(type,records){const xlsx=getXlsx();const wb=xlsx.utils.book_new();const cols=mainColumns(type);const head=[...cols.map(c=>c.label),'交通路線摘要（僅供檢視）',statusHeading];const rows=records.map(r=>[...cols.map(c=>(Array.isArray(r[c.key])?r[c.key].join("\n"):(r[c.key]&&typeof r[c.key]==="object"?JSON.stringify(r[c.key]):r[c.key]??""))),routeSummary(r),r.is_published?'已上架':'草稿']);xlsx.utils.book_append_sheet(wb,sheet(xlsx,head,rows),MAIN);xlsx.utils.book_append_sheet(wb,sheet(xlsx,routeColumns,routeRows(records)),ROUTES);if(type==='trips')xlsx.utils.book_append_sheet(wb,sheet(xlsx,sectionColumns,sectionRows(records)),SECTIONS);xlsx.utils.book_append_sheet(wb,sheet(xlsx,relatedColumns,relatedRows(records)),RELATED);const help=[['北投旅圖｜'+categoryLabel(type)+'資料匯入匯出說明',''],['工作表','用途'],['主資料','每篇文章一列。資料編號（ID）及名稱必填；同 ID 更新原資料，新 ID 新增草稿。'],['交通路線','實際交通資料請在「交通路線」工作表編輯；主資料的交通摘要僅供檢視，不參與匯入。'],['行程分段','僅行程類別使用，每一列是一個段落。'],['延伸閱讀','每列一篇關聯文章；文章類型請填 spots、foods、trips、stories。'],['上架狀態','僅供參考，匯入不會改變既有文章的上架狀態；新文章維持草稿。'],['更新安全','主資料與匯入使用同一套欄位；舊版 transport_metro／bus／car 已不在主資料顯示。交通路線以獨立工作表匯入；沒有列出交通／分段／延伸閱讀的文章，保留資料庫既有內容。'],['重要提醒','請先匯出最新資料並備份；若更新已上架文章，前台內容也會同步變更。'],['交通分鐘','路段分鐘填數字，例如 7；未填不猜測。全程分鐘由前台自動加總。'],['不支援','請勿重新命名工作表及欄位標題，勿將 Excel 儲存為舊版 .xls。']];xlsx.utils.book_append_sheet(wb,sheet(xlsx,['項目','說明'],help),HELP);return wb;}
function download(type,records){const xlsx=getXlsx();const wb=toWorkbook(type,records);const day=new Date().toLocaleDateString('sv-SE');xlsx.writeFile(wb,`北投旅圖_${categoryLabel(type)}_完整資料_${day}.xlsx`,{compression:true});return records.length;}
function rowsOf(xlsx,wb,name){const s=wb.Sheets[name];return s?xlsx.utils.sheet_to_json(s,{defval:'',raw:false}):null;}
function parseExcel(type,buffer){const xlsx=getXlsx();const wb=xlsx.read(buffer,{type:'array',cellDates:false});const raw=rowsOf(xlsx,wb,MAIN);if(!raw)throw Error('找不到「主資料」工作表；請使用本後台匯出的 Excel 範本。');const cols=mainColumns(type);const mapping=new Map(cols.flatMap(c=>[[c.label,c.key],[c.key,c.key]]));const headers=Object.keys(raw[0]||{});if(!headers.some(h=>mapping.get(h)==='id')||!headers.some(h=>mapping.get(h)==='title'))throw Error('主資料缺少「ID／名稱」欄位；請勿更改 Excel 表頭。');const records=raw.map((r,i)=>{const item={};for(const [heading,value] of Object.entries(r)){const key=mapping.get(heading);if(!key)continue;if(key==='sort_order')item[key]=str(value)===''?null:Number(value);else item[key]=safeText(value);}item.__row=i+2;return item;}).filter(item=>Object.entries(item).some(([k,v])=>k!=='__row'&&str(v)!==''));
 const index=new Map(records.map(r=>[str(r.id),r]));
 const transit=rowsOf(xlsx,wb,ROUTES);if(transit){const grouped=new Map();for(const [i,r] of transit.entries()){const id=str(r['資料編號']);if(!id)continue;if(!index.has(id))throw Error(`交通路線第 ${i+2} 列的資料編號 ${id} 不在「主資料」中`);const routeN=Number(r['路線序號']);const stepN=Number(r['節點序號']);if(!Number.isInteger(routeN)||routeN<1||!Number.isInteger(stepN)||stepN<1)throw Error(`交通路線第 ${i+2} 列的路線或節點序號無效`);const typeName=str(r['節點類型'])||'站點';if(!['站點','抵達','步行','捷運','公車','轉乘','自行車','候車','接駁'].includes(typeName))throw Error(`交通路線第 ${i+2} 列的節點類型無效：${typeName}`);const duration=str(r['分鐘']);if(duration&&!Number.isFinite(global.MetroTransitDuration?.minutes(duration)))throw Error(`交通路線第 ${i+2} 列的分鐘格式無效：${duration}`);const group=grouped.get(id)||new Map();const route=group.get(routeN)||{title:str(r['路線名稱'])||'大眾運輸推薦路線',enabled:str(r['啟用'])!=='否',steps:[]};if(route.steps.some(s=>s.__order===stepN))throw Error(`交通路線第 ${i+2} 列重複節點序號 ${stepN}`);route.steps.push({__order:stepN,type:typeName,name:str(r['站名']),line:str(r['路線／車號']),direction:str(r['方向']),duration:duration?(global.MetroTransitDuration.minutes(duration)).toString():'',distance:str(r['距離']),detail:str(r['備註'])});group.set(routeN,route);grouped.set(id,group);}
 for(const [id,group] of grouped){index.get(id).transport_routes=[...group.entries()].sort((a,b)=>a[0]-b[0]).map(([,r])=>{r.steps.sort((a,b)=>a.__order-b.__order).forEach(s=>delete s.__order);if(!r.steps.length||!['站點','抵達'].includes(r.steps[0].type)||!['站點','抵達'].includes(r.steps[r.steps.length-1].type))throw Error(id+' 的路線首尾必須有起點與目的地站點');if(r.steps.some(s=>['站點','抵達'].includes(s.type)&&!s.name))throw Error(id+' 有未填名稱的站點');return r;});}}
 const sections=rowsOf(xlsx,wb,SECTIONS);if(type==='trips'&&sections){const grouped=new Map();for(const [i,r] of sections.entries()){const id=str(r['資料編號']);if(!id)continue;if(!index.has(id))throw Error(`行程分段第 ${i+2} 列的 ID ${id} 不在「主資料」`);const order=Number(r['段落序號']);if(!Number.isInteger(order)||order<1)throw Error(`行程分段第 ${i+2} 列序號錯誤`);if(!str(r['段落標題']))throw Error(`行程分段第 ${i+2} 列未填段落標題`);const list=grouped.get(id)||[];if(list.some(s=>s.order===order))throw Error(id+' 行程分段序號重複：'+order);const showImage=str(r['顯示圖片']);list.push({order,time:str(r['時間']),title:str(r['段落標題']),text:str(r['段落說明']),show_image:showImage===''?true:!['否','false','0','不顯示'].includes(showImage.toLowerCase()),image:str(r['圖片網址']),image_source:str(r['圖片來源'])});grouped.set(id,list);}for(const [id,list] of grouped)index.get(id).trip_sections=list.sort((a,b)=>a.order-b.order);}
 const related=rowsOf(xlsx,wb,RELATED);if(related){const grouped=new Map();for(const [i,r] of related.entries()){const id=str(r['資料編號']);if(!id)continue;if(!index.has(id))throw Error(`延伸閱讀第 ${i+2} 列的 ID ${id} 不在主資料`);const linkType=str(r['文章類型']),linkId=str(r['關聯文章編號']);if(!['spots','foods','trips','stories'].includes(linkType)||!linkId)throw Error(`延伸閱讀第 ${i+2} 列文章類型或編號錯誤`);const list=grouped.get(id)||[];list.push({order:Number(r['排序'])||i+1,type:linkType,id:linkId});grouped.set(id,list);}for(const [id,list] of grouped)index.get(id).related_items=list.sort((a,b)=>a.order-b.order).map(({type,id})=>({type,id}));}
 return records.map(({__row,...r})=>r);
}
async function parseFile(type,file){if(!file)throw Error('尚未選取檔案');const ext=file.name.split('.').pop().toLowerCase();if(ext==='xlsx')return parseExcel(type,await file.arrayBuffer());if(ext==='json'){let raw;try{raw=JSON.parse(await file.text());}catch(e){throw Error('JSON 內容無法解析：'+e.message);}if(!Array.isArray(raw))throw Error('JSON 最外層必須是文章陣列');return raw;}throw Error('只支援 .xlsx 或 .json，請勿使用舊版 .xls');}
function clean(type,records){if(!Array.isArray(records)||!records.length||records.length>500)throw Error('單次匯入請選擇 1～500 筆資料');const allowed=new Map(global.MetroCmsSchema.fields(type).map(([key,,kind])=>[key,kind]));if(type==='trips')allowed.set('transport_routes','json');allowed.set('related_items','json');const ids=new Set(),warnings=[];const prepared=records.map((row,i)=>{if(!row||typeof row!=='object'||Array.isArray(row))throw Error('第 '+(i+1)+' 筆不是文章物件');const id=str(row.id),title=str(row.title);if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,99}$/.test(id))throw Error(`第 ${i+1} 筆資料編號錯誤或空白`);if(ids.has(id))throw Error('重複的資料編號：'+id);ids.add(id);if(!title)throw Error(id+' 缺少名稱');let item={id,title};for(const [key,raw] of Object.entries(row)){if(key==='id'||key==='title'||key==='is_published'||key.startsWith('__'))continue;if(key==='slug'&&!str(raw))continue;if(!allowed.has(key)){warnings.push(id+' 略過不支援欄位 '+key);continue;}if(['review_status','review_note','reviewed_at','reviewed_by'].includes(key))continue;const kind=allowed.get(key);if(['transport_routes','trip_sections','related_items'].includes(key)){let arr=raw;if(typeof raw==='string'){try{arr=JSON.parse(raw);}catch{throw Error(id+' 的 '+key+' 不是合法 JSON 陣列');}}if(!Array.isArray(arr))throw Error(id+' 的 '+key+' 必須是陣列');item[key]=arr;}
 else if(kind==='number'){if(raw===''||raw===null||raw===undefined)continue;else if(!Number.isFinite(Number(raw)))throw Error(id+' 的 '+key+' 必須是數字');else item[key]=Number(raw);}
 else if(kind==='boolean'){}else item[key]=raw===null?null:safeText(raw);}
 if(item.transport_routes){for(const route of item.transport_routes){if(!route||!Array.isArray(route.steps)||!route.steps.length)throw Error(id+' 交通路線缺少節點');}}
 if(type==='trips'&&item.trip_sections&&item.trip_sections.some(s=>!s||!str(s.title)))throw Error(id+' 行程分段缺少標題');return item;});return {records:prepared,warnings};}
async function all(db,type){const output=[];for(let start=0;start<20000;start+=500){const {data,error}=await db.from(type).select('*').order('sort_order',{ascending:true}).range(start,start+499);if(error)throw Error('讀取完整資料失敗：'+error.message);output.push(...data);if(data.length<500)return output;}throw Error('資料筆數超過 20,000，請聯絡管理員調整匯出上限');}
async function existing(db,type,ids){const map=new Map();for(let i=0;i<ids.length;i+=100){const {data,error}=await db.from(type).select('id,is_published').in('id',ids.slice(i,i+100));if(error)throw Error('查詢既有資料失敗：'+error.message);for(const r of data||[])map.set(String(r.id),r);}return map;}
async function write(db,type,records,known,onProgress){let done=0,created=0,updated=0;for(const item of records){const old=known.get(String(item.id));const payload={...item};if(old){delete payload.id;delete payload.is_published;}else{payload.is_published=false;payload.review_status='pending';if(!str(payload.slug))payload.slug=item.id.toLowerCase();if(type==='trips'&&!Array.isArray(payload.trip_sections))throw Error(item.id+' 是新行程，請提供「行程分段」工作表資料');}
 const q=old?db.from(type).update(payload).eq('id',item.id):db.from(type).insert(payload);const {data,error}=await q.select('id');if(error||!data?.length)throw Error(`已寫入 ${done}/${records.length} 筆，${item.id} 失敗：${error?.message||'讀不到寫入確認'}。請先重新匯出確認，勿直接整包重試。`);
 // 逐筆讀回關鍵交通與行程欄位，避免 RPC／欄位映射造成「匯入成功但交通空白」。
 const checkKeys=['station','transport_routes','trip_sections'].filter(k=>Object.prototype.hasOwnProperty.call(item,k));if(checkKeys.length){const {data:check,error:checkError}=await db.from(type).select(['id',...checkKeys].join(',')).eq('id',item.id).single();if(checkError||!check)throw Error(item.id+' 已寫入，但交通／行程欄位讀回失敗：'+(checkError?.message||'無資料'));for(const key of checkKeys){if(Array.isArray(item[key])){if(!Array.isArray(check[key])||check[key].length!==item[key].length)throw Error(item.id+' 的 '+key+' 寫入後內容不完整，請檢查資料庫');if(key==='transport_routes'){item[key].forEach((route,i)=>{const actual=check[key][i];if(!Array.isArray(actual?.steps)||actual.steps.length!==(route.steps||[]).length)throw Error(item.id+' 的第 '+(i+1)+' 條交通路線節點讀回不完整');route.steps.forEach((step,j)=>{const found=actual.steps[j]||{};for(const field of ['type','name','line','direction','duration','distance','detail'])if(safeText(step[field])!==safeText(found[field]))throw Error(item.id+' 的第 '+(i+1)+' 條路線、第 '+(j+1)+' 節點 '+field+' 寫入不一致');});});}if(key==='trip_sections')item[key].forEach((part,i)=>{if(safeText(part.title)!==safeText(check[key][i]?.title))throw Error(item.id+' 的行程分段標題寫入不一致');});}else if(safeText(check[key])!==safeText(item[key]))throw Error(item.id+' 的 '+key+' 寫入後不一致，請檢查資料庫');}}
 done++;old?updated++:created++;onProgress?.(done,records.length);}
 return {done,created,updated};}
global.MetroBulkData=Object.freeze({CATEGORIES,fields,mainColumns,toWorkbook,parseExcel,parseFile,clean,all,existing,write,download});
})(window);
